### ISSUE TITLE
post/patch collection or entity

### ISSUE THREAD

**Issue by CreativeNative** [theDisco/traum#7]
traum/src/Resource/Listing.php::322

Shouldn't we post a collection instead of an entity? Please check the ToDo's.

I think actually we post every entity for it's own. With a Collection we would have only one post, wouldn't we?

```
public function postLeisureActivities($listingId, Entity\ListingLeisureActivityCollection  $listingLeisureActivityCollection)
```

or

```
public function postLeisureActivities($listingId, Entity\ListingLeisureActivity $listingLeisureActivity)
{
    $uri = sprintf('/listing/%d/leisure-activity', $listingId);
    $body = $this->executePost($uri, $listingLeisureActivity, new Transformer\ListingLeisureActivity);

    return new Entity\ListingLeisureActivity($body);
}
```

**Comment by theDisco** [comment]
As I wrote in your pull request I am not sure if you can actually post a collection to this endpoint. Posting a collection to this endpoint would also require a slightly different transformer. I think that they use the word `collection` in this context because it is the right word to use in the RESTful API terminology. Maybe you can talk to the devs who wrote it to explain us if that is possible at all.

**Comment by CreativeNative** [comment]
The API documentation says: "The LeisureActivity POST collection allows the creation of new **leisure activities** for the specified listing. Each activity must be unique." They speak about the plural, but its not quite sure if they mean with one or several posts.

A collection in OOP is a wrapper around an array of objects and I think it's the same in the RESTful API terminology or am I wrong?

I wrote an e-mail to the devs. If we have the answer I will do the changes for the pull request #3.

**Comment by theDisco** [comment]
If you post and entity, it works as expected, did you actually try posting a collection?

**Comment by CreativeNative** [comment]
Traum Dev wrote:
Many of our services support POST Collections, including leisure-activity and week-price-table. As an an example:

```
{…}
```

The syntax for 2 (or more) entities, only possible for Collection methods :

```
[
    {…},
    {…}
]
```
